/** Legacy React paths → canonical URL paths (301-style via replaceState in App). */
export const ROUTE_REDIRECTS = {
  "/16-best-christmas-gifts-for-seniors-amazon-2026": "/16-best-christmas-gifts-for-seniors-amazon-2025",
  "/20-thoughtful-inexpensive-christmas-gift-ideas-for-senior-citizens-under-20": "/inexpensive-christmas-gift-ideas-for-senior-citizens",
  "/3-foods-for-seniors-to-avoid": "/3-foods-seniors-should-avoid",
  "/amir-abbasi": "/author-amir-abbasi",
  "/best-heavy-duty-walkers-for-obese-seniors-top-5-picks-for-2026": "/best-heavy-duty-walkers-for-obese-seniors",
  "/best-upright-walkers-for-outdoor-use-top-5-picks-from-amazon-2026-edition": "/best-upright-walkers-for-outdoor-use-2025",
  "/best-walking-shoes-for-seniors-in-2026": "/best-walking-shoes-for-seniors-2026",
  "/buying-a-walker-dont-make-a-move-until-you-read-this": "/tips-for-choosing-and-using-walkers-a-comprehensive-guide",
  "/caregivers-guide-to-helping-seniors-pick-and-use-the-perfect-walker": "/caregivers-guide-to-senior-walker-selection-and-usage",
  "/christmas-gift-ideas-for-elderly-ladies-this-december-2026": "/christmas-gift-ideas-for-elderly-ladies-december-2025",
  "/compact-walkers-for-seniors-a-comprehensive-guide": "/compact-walkers-for-seniors",
  "/contact": "/contact-us",
  "/cookies-policy": "/cookies",
  "/elenker-vs-nova-upright-walkers-2026": "/elenker-vs-nova-upright-walkers-2025",
  "/emergency-preparedness-for-walker-users-top-medical-alert-devices-smart-tech": "/emergency-preparedness-for-walker-users",
  "/every-way-to-return-amazon-orders-for-free": "/free-amazon-returns-guide",
  "/got-a-walker-with-large-wheels-try-these-game-changing-tips-for-seniors": "/how-to-use-walker-large-wheels-seniors-safely",
  "/heavy-duty-walkers-for-tall-people-top-picks": "/heavy-duty-walkers-for-tall-people",
  "/holiday-safety-tips-for-seniors-prevent-falls-fires-seasonal-risks": "/holiday-safety-tips-for-seniors",
  "/holiday-safety-tips-for-seniors-using-walkers": "/holiday-safety-tips-seniors-using-walkers",
  "/how-to-adjust-a-walker-to-the-correct-height-a-safety-checklist": "/how-to-adjust-a-walker-to-the-correct-height",
  "/how-to-travel-with-a-walker-tips-for-seniors": "/how-to-travel-with-a-walker",
  "/mental-health-in-old-age-a-complete-guide-for-seniors-caregivers": "/mental-health-in-old-age",
  "/most-people-use-walkers-wrong-are-you-making-these-mistakes": "/what-is-the-proper-way-to-use-a-walker",
  "/rain-snow-or-shine-how-to-stay-safe-with-your-walker": "/walker-safety-tips-for-all-weather-conditions",
  "/replacement-walker-hand-grips-for-all-sizes-at-walmart": "/replacement-walker-hand-grips-for-all-kinds-of-walkers",
  "/robin-dolan": "/author-robin-dolan",
  "/social-activities-for-older-adults-the-best-ways-to-stay-connected-active-and-happy": "/social-activities-for-older-adults",
  "/stop-the-struggle-the-ultimate-easy-guide-to-fitting-a-walker-for-seniors": "/an-easy-guide-on-how-to-fit-a-walker-for-seniors",
  "/struggling-with-a-walker-in-a-small-home-try-these-space-saving-hacks": "/tips-using-walker-small-homes",
  "/syed-ali": "/author-syed-ali",
  "/the-7-best-places-to-buy-walkers-for-seniors": "/where-to-buy-walkers-for-seniors-top-brands-reviews",
  "/the-best-holiday-gifts-for-seniors-who-have-everything": "/best-holiday-gifts-for-seniors-who-have-everything",
  "/the-complete-guide-to-walker-and-rollator-types-which-one-fits-you-best": "/types-of-medical-walkers-and-rollators-a-comprehensive-guide",
  "/the-must-have-walker-safety-features-every-senior-should-know-about": "/important-safety-features-walkers-for-seniors",
  "/tools": "/best-tools",
  "/top-4-walkers-with-seats-for-seniors-find-your-perfect-fit": "/best-4-wheel-walkers-with-seats",
  "/understanding-upright-walkers-how-they-improve-senior-posture": "/understanding-upright-walkers-senior-posture",
  "/valentines-day-gift-ideas-for-seniors-to-give-to-each-other": "/valentines-day-gift-ideas-for-seniors",
  "/valentines-day-ideas-what-seniors-can-give-each-other": "/valentines-day-ideas",
  "/will-medicare-really-pay-for-your-walker-the-truth-every-senior-should-know": "/does-medicare-pay-for-walkers-for-seniors",
};

export function resolveRoutePath(pathname) {
  const path = (pathname || '/').replace(/\/+$/, '') || '/';
  return ROUTE_REDIRECTS[path] ?? path;
}
