/** Canonical URLs match browser paths (thewalkeradvisor.com). */
import { normalizeRoutePath } from './pathUtils';

export const ROUTE_CANONICALS = {
  "/": "https://thewalkeradvisor.com/",
  "/16-best-christmas-gifts-for-seniors-amazon-2025": "https://thewalkeradvisor.com/16-best-christmas-gifts-for-seniors-amazon-2025/",
  "/3-foods-seniors-should-avoid": "https://thewalkeradvisor.com/3-foods-seniors-should-avoid/",
  "/5-best-upright-walkers-for-seniors-find-the-right-one": "https://thewalkeradvisor.com/5-best-upright-walkers-for-seniors-find-the-right-one/",
  "/about-us": "https://thewalkeradvisor.com/about-us/",
  "/an-easy-guide-on-how-to-fit-a-walker-for-seniors": "https://thewalkeradvisor.com/an-easy-guide-on-how-to-fit-a-walker-for-seniors/",
  "/articles": "https://thewalkeradvisor.com/articles/",
  "/author-amir-abbasi": "https://thewalkeradvisor.com/author-amir-abbasi/",
  "/author-robin-dolan": "https://thewalkeradvisor.com/author-robin-dolan/",
  "/author-syed-ali": "https://thewalkeradvisor.com/author-syed-ali/",
  "/best-4-wheel-walkers-with-seats": "https://thewalkeradvisor.com/best-4-wheel-walkers-with-seats/",
  "/best-heavy-duty-walkers-for-obese-seniors": "https://thewalkeradvisor.com/best-heavy-duty-walkers-for-obese-seniors/",
  "/best-holiday-gifts-for-seniors-who-have-everything": "https://thewalkeradvisor.com/best-holiday-gifts-for-seniors-who-have-everything/",
  "/best-mobility-devices-for-seniors": "https://thewalkeradvisor.com/best-mobility-devices-for-seniors/",
  "/best-small-walkers-for-seniors-top-4-options": "https://thewalkeradvisor.com/best-small-walkers-for-seniors-top-4-options/",
  "/best-tools": "https://thewalkeradvisor.com/best-tools/",
  "/best-travel-walkers-for-seniors-2025": "https://thewalkeradvisor.com/best-travel-walkers-for-seniors-2025/",
  "/best-upright-walkers-for-outdoor-use-2025": "https://thewalkeradvisor.com/best-upright-walkers-for-outdoor-use-2025/",
  "/best-walking-shoes-for-seniors-2026": "https://thewalkeradvisor.com/best-walking-shoes-for-seniors-2026/",
  "/can-heart-issues-increase-fall-risk-in-seniors": "https://thewalkeradvisor.com/can-heart-issues-increase-fall-risk-in-seniors/",
  "/can-osteoarthritis-lead-to-more-falls-in-seniors": "https://thewalkeradvisor.com/can-osteoarthritis-lead-to-more-falls-in-seniors/",
  "/caregivers-corner": "https://thewalkeradvisor.com/caregivers-corner/",
  "/caregivers-guide-to-senior-walker-selection-and-usage": "https://thewalkeradvisor.com/caregivers-guide-to-senior-walker-selection-and-usage/",
  "/christmas-gift-ideas-for-elderly-ladies-december-2025": "https://thewalkeradvisor.com/christmas-gift-ideas-for-elderly-ladies-december-2025/",
  "/compact-walkers-for-seniors": "https://thewalkeradvisor.com/compact-walkers-for-seniors/",
  "/contact-us": "https://thewalkeradvisor.com/contact-us/",
  "/cookies": "https://thewalkeradvisor.com/cookies/",
  "/disclaimer": "https://thewalkeradvisor.com/disclaimer/",
  "/does-medicare-pay-for-walkers-for-seniors": "https://thewalkeradvisor.com/does-medicare-pay-for-walkers-for-seniors/",
  "/elenker-vs-nova-upright-walkers-2025": "https://thewalkeradvisor.com/elenker-vs-nova-upright-walkers-2025/",
  "/emergency-preparedness-for-walker-users": "https://thewalkeradvisor.com/emergency-preparedness-for-walker-users/",
  "/free-amazon-returns-guide": "https://thewalkeradvisor.com/free-amazon-returns-guide/",
  "/heavy-duty-walkers-for-tall-people": "https://thewalkeradvisor.com/heavy-duty-walkers-for-tall-people/",
  "/holiday-safety-tips-for-seniors": "https://thewalkeradvisor.com/holiday-safety-tips-for-seniors/",
  "/holiday-safety-tips-seniors-using-walkers": "https://thewalkeradvisor.com/holiday-safety-tips-seniors-using-walkers/",
  "/how-do-supportive-grips-on-walkers-help-seniors-with-mobility": "https://thewalkeradvisor.com/how-do-supportive-grips-on-walkers-help-seniors-with-mobility/",
  "/how-to-adjust-a-walker-to-the-correct-height": "https://thewalkeradvisor.com/how-to-adjust-a-walker-to-the-correct-height/",
  "/how-to-choose-walking-shoes-for-balance-and-stability": "https://thewalkeradvisor.com/how-to-choose-walking-shoes-for-balance-and-stability/",
  "/how-to-transition-from-a-walker-to-walking-independently": "https://thewalkeradvisor.com/how-to-transition-from-a-walker-to-walking-independently/",
  "/how-to-travel-with-a-walker": "https://thewalkeradvisor.com/how-to-travel-with-a-walker/",
  "/how-to-use-a-walker-with-wheels": "https://thewalkeradvisor.com/how-to-use-a-walker-with-wheels/",
  "/how-to-use-walker-large-wheels-seniors-safely": "https://thewalkeradvisor.com/how-to-use-walker-large-wheels-seniors-safely/",
  "/important-safety-features-walkers-for-seniors": "https://thewalkeradvisor.com/important-safety-features-walkers-for-seniors/",
  "/inexpensive-christmas-gift-ideas-for-senior-citizens": "https://thewalkeradvisor.com/inexpensive-christmas-gift-ideas-for-senior-citizens/",
  "/mental-health-in-old-age": "https://thewalkeradvisor.com/mental-health-in-old-age/",
  "/must-have-walker-accessories-to-make-life-easier-and-safer": "https://thewalkeradvisor.com/must-have-walker-accessories-to-make-life-easier-and-safer/",
  "/privacy-policy": "https://thewalkeradvisor.com/privacy-policy/",
  "/replacement-walker-hand-grips-for-all-kinds-of-walkers": "https://thewalkeradvisor.com/replacement-walker-hand-grips-for-all-kinds-of-walkers/",
  "/senior-safety-how-to-use-a-walker-on-stairs": "https://thewalkeradvisor.com/senior-safety-how-to-use-a-walker-on-stairs/",
  "/social-activities-for-older-adults": "https://thewalkeradvisor.com/social-activities-for-older-adults/",
  "/terms-and-conditions": "https://thewalkeradvisor.com/terms-and-conditions/",
  "/the-secret-amazon-shopping-hack-to-get-a-deal-on-just-about-anything": "https://thewalkeradvisor.com/the-secret-amazon-shopping-hack-to-get-a-deal-on-just-about-anything/",
  "/the-side-effects-of-using-a-cane": "https://thewalkeradvisor.com/the-side-effects-of-using-a-cane/",
  "/tips-for-choosing-and-using-walkers-a-comprehensive-guide": "https://thewalkeradvisor.com/tips-for-choosing-and-using-walkers-a-comprehensive-guide/",
  "/tips-using-walker-small-homes": "https://thewalkeradvisor.com/tips-using-walker-small-homes/",
  "/types-of-medical-walkers-and-rollators-a-comprehensive-guide": "https://thewalkeradvisor.com/types-of-medical-walkers-and-rollators-a-comprehensive-guide/",
  "/understanding-upright-walkers-senior-posture": "https://thewalkeradvisor.com/understanding-upright-walkers-senior-posture/",
  "/valentines-day-gift-ideas-for-seniors": "https://thewalkeradvisor.com/valentines-day-gift-ideas-for-seniors/",
  "/valentines-day-ideas": "https://thewalkeradvisor.com/valentines-day-ideas/",
  "/walker-safety-tips-for-all-weather-conditions": "https://thewalkeradvisor.com/walker-safety-tips-for-all-weather-conditions/",
  "/what-is-the-proper-way-to-use-a-walker": "https://thewalkeradvisor.com/what-is-the-proper-way-to-use-a-walker/",
  "/where-to-buy-walkers-for-seniors-top-brands-reviews": "https://thewalkeradvisor.com/where-to-buy-walkers-for-seniors-top-brands-reviews/",
  "/why-seniors-need-proper-walking-shoes": "https://thewalkeradvisor.com/why-seniors-need-proper-walking-shoes/",
};

const SITE_ORIGIN = 'https://thewalkeradvisor.com';

export function getCanonicalForRoute(pathname) {
  const path = normalizeRoutePath(pathname);
  return ROUTE_CANONICALS[path] ?? (path === '/' ? `${SITE_ORIGIN}/` : `${SITE_ORIGIN}${path}/`);
}
