/** Maps React router paths to production canonical URLs from live WordPress. */
export const ROUTE_CANONICALS = {
  "/": "https://thewalkeradvisor.com/",
  "/16-best-christmas-gifts-for-seniors-amazon-2026": "https://thewalkeradvisor.com/16-best-christmas-gifts-for-seniors-amazon-2025/",
  "/20-thoughtful-inexpensive-christmas-gift-ideas-for-senior-citizens-under-20": "https://thewalkeradvisor.com/inexpensive-christmas-gift-ideas-for-senior-citizens/",
  "/3-foods-for-seniors-to-avoid": "https://thewalkeradvisor.com/3-foods-seniors-should-avoid/",
  "/5-best-upright-walkers-for-seniors-find-the-right-one": "https://thewalkeradvisor.com/5-best-upright-walkers-for-seniors-find-the-right-one/",
  "/about-us": "https://thewalkeradvisor.com/about-us/",
  "/amir-abbasi": "https://thewalkeradvisor.com/author-amir-abbasi/",
  "/articles": "https://thewalkeradvisor.com/articles/",
  "/best-heavy-duty-walkers-for-obese-seniors-top-5-picks-for-2026": "https://thewalkeradvisor.com/best-heavy-duty-walkers-for-obese-seniors/",
  "/best-mobility-devices-for-seniors": "https://thewalkeradvisor.com/best-mobility-devices-for-seniors/",
  "/best-small-walkers-for-seniors-top-4-options": "https://thewalkeradvisor.com/best-small-walkers-for-seniors-top-4-options/",
  "/best-travel-walkers-for-seniors-2025": "https://thewalkeradvisor.com/best-travel-walkers-for-seniors-2025/",
  "/best-upright-walkers-for-outdoor-use-top-5-picks-from-amazon-2026-edition": "https://thewalkeradvisor.com/best-upright-walkers-for-outdoor-use-2025/",
  "/best-walking-shoes-for-seniors-in-2026": "https://thewalkeradvisor.com/best-walking-shoes-for-seniors-2026/",
  "/buying-a-walker-dont-make-a-move-until-you-read-this": "https://thewalkeradvisor.com/tips-for-choosing-and-using-walkers-a-comprehensive-guide/",
  "/can-heart-issues-increase-fall-risk-in-seniors": "https://thewalkeradvisor.com/can-heart-issues-increase-fall-risk-in-seniors/",
  "/can-osteoarthritis-lead-to-more-falls-in-seniors": "https://thewalkeradvisor.com/can-osteoarthritis-lead-to-more-falls-in-seniors/",
  "/caregivers-corner": "https://thewalkeradvisor.com/caregivers-corner/",
  "/caregivers-guide-to-helping-seniors-pick-and-use-the-perfect-walker": "https://thewalkeradvisor.com/caregivers-guide-to-senior-walker-selection-and-usage/",
  "/christmas-gift-ideas-for-elderly-ladies-this-december-2026": "https://thewalkeradvisor.com/christmas-gift-ideas-for-elderly-ladies-this-december-2026/",
  "/compact-walkers-for-seniors-a-comprehensive-guide": "https://thewalkeradvisor.com/compact-walkers-for-seniors/",
  "/contact": "https://thewalkeradvisor.com/contact-us/",
  "/cookies-policy": "https://thewalkeradvisor.com/cookies/",
  "/disclaimer": "https://thewalkeradvisor.com/disclaimer/",
  "/emergency-preparedness-for-walker-users-top-medical-alert-devices-smart-tech": "https://thewalkeradvisor.com/emergency-preparedness-for-walker-users/",
  "/every-way-to-return-amazon-orders-for-free": "https://thewalkeradvisor.com/free-amazon-returns-guide/",
  "/got-a-walker-with-large-wheels-try-these-game-changing-tips-for-seniors": "https://thewalkeradvisor.com/best-wheel-size-for-walkers/",
  "/heavy-duty-walkers-for-tall-people-top-picks": "https://thewalkeradvisor.com/heavy-duty-walkers-for-tall-people/",
  "/holiday-safety-tips-for-seniors-prevent-falls-fires-seasonal-risks": "https://thewalkeradvisor.com/holiday-safety-tips-for-seniors/",
  "/holiday-safety-tips-for-seniors-using-walkers": "https://thewalkeradvisor.com/holiday-safety-tips-seniors-using-walkers/",
  "/how-do-supportive-grips-on-walkers-help-seniors-with-mobility": "https://thewalkeradvisor.com/how-do-supportive-grips-on-walkers-help-seniors-with-mobility/",
  "/how-to-adjust-a-walker-to-the-correct-height-a-safety-checklist": "https://thewalkeradvisor.com/how-to-adjust-a-walker-to-the-correct-height/",
  "/how-to-choose-walking-shoes-for-balance-and-stability": "https://thewalkeradvisor.com/how-to-choose-walking-shoes-for-balance-and-stability/",
  "/how-to-transition-from-a-walker-to-walking-independently": "https://thewalkeradvisor.com/how-to-transition-from-a-walker-to-walking-independently/",
  "/how-to-travel-with-a-walker-tips-for-seniors": "https://thewalkeradvisor.com/how-to-travel-with-a-walker/",
  "/how-to-use-a-walker-with-wheels": "https://thewalkeradvisor.com/how-to-use-a-walker-with-wheels/",
  "/mental-health-in-old-age-a-complete-guide-for-seniors-caregivers": "https://thewalkeradvisor.com/mental-health-in-old-age/",
  "/most-people-use-walkers-wrong-are-you-making-these-mistakes": "https://thewalkeradvisor.com/what-is-the-proper-way-to-use-a-walker/",
  "/must-have-walker-accessories-to-make-life-easier-and-safer": "https://thewalkeradvisor.com/must-have-walker-accessories-to-make-life-easier-and-safer/",
  "/privacy-policy": "https://thewalkeradvisor.com/privacy-policy/",
  "/rain-snow-or-shine-how-to-stay-safe-with-your-walker": "https://thewalkeradvisor.com/walker-safety-tips-for-all-weather-conditions/",
  "/replacement-walker-hand-grips-for-all-kinds-of-walkers": "https://thewalkeradvisor.com/replacement-walker-hand-grips-for-all-kinds-of-walkers/",
  "/replacement-walker-hand-grips-for-all-sizes-at-walmart": "https://thewalkeradvisor.com/replacement-walker-hand-grips-for-all-kinds-of-walkers/",
  "/robin-dolan": "https://thewalkeradvisor.com/author-robin-dolan/",
  "/senior-safety-how-to-use-a-walker-on-stairs": "https://thewalkeradvisor.com/senior-safety-how-to-use-a-walker-on-stairs/",
  "/social-activities-for-older-adults-the-best-ways-to-stay-connected-active-and-happy": "https://thewalkeradvisor.com/social-activities-for-older-adults/",
  "/stop-the-struggle-the-ultimate-easy-guide-to-fitting-a-walker-for-seniors": "https://thewalkeradvisor.com/an-easy-guide-on-how-to-fit-a-walker-for-seniors/",
  "/struggling-with-a-walker-in-a-small-home-try-these-space-saving-hacks": "https://thewalkeradvisor.com/tips-using-walker-small-homes/",
  "/syed-ali": "https://thewalkeradvisor.com/author-syed-ali/",
  "/terms-and-conditions": "https://thewalkeradvisor.com/terms-and-conditions/",
  "/the-7-best-places-to-buy-walkers-for-seniors": "https://thewalkeradvisor.com/where-to-buy-walkers-for-seniors-top-brands-reviews/",
  "/the-best-holiday-gifts-for-seniors-who-have-everything": "https://thewalkeradvisor.com/best-holiday-gifts-for-seniors-who-have-everything/",
  "/the-complete-guide-to-walker-and-rollator-types-which-one-fits-you-best": "https://thewalkeradvisor.com/types-of-medical-walkers-and-rollators-a-comprehensive-guide/",
  "/the-must-have-walker-safety-features-every-senior-should-know-about": "https://thewalkeradvisor.com/safest-walkers-for-seniors-top-5-choices/",
  "/the-secret-amazon-shopping-hack-to-get-a-deal-on-just-about-anything": "https://thewalkeradvisor.com/the-secret-amazon-shopping-hack-to-get-a-deal-on-just-about-anything/",
  "/the-side-effects-of-using-a-cane": "https://thewalkeradvisor.com/the-side-effects-of-using-a-cane/",
  "/tools": "https://thewalkeradvisor.com/best-tools/",
  "/top-4-walkers-with-seats-for-seniors-find-your-perfect-fit": "https://thewalkeradvisor.com/best-4-wheel-walkers-with-seats/",
  "/understanding-upright-walkers-how-they-improve-senior-posture": "https://thewalkeradvisor.com/understanding-upright-walkers-senior-posture/",
  "/valentines-day-gift-ideas-for-seniors-to-give-to-each-other": "https://thewalkeradvisor.com/valentines-day-gift-ideas-for-seniors/",
  "/valentines-day-ideas-what-seniors-can-give-each-other": "https://thewalkeradvisor.com/valentines-day-ideas/",
  "/why-seniors-need-proper-walking-shoes": "https://thewalkeradvisor.com/why-seniors-need-proper-walking-shoes/",
  "/will-medicare-really-pay-for-your-walker-the-truth-every-senior-should-know": "https://thewalkeradvisor.com/does-medicare-pay-for-walkers-for-seniors/",
};

const SITE_ORIGIN = 'https://thewalkeradvisor.com';

/** Canonical = same URL as the React route (self-referencing). */
export function getCanonicalForRoute(pathname) {
  const path = (pathname || '/').replace(/\/+$/, '') || '/';
  return path === '/' ? `${SITE_ORIGIN}/` : `${SITE_ORIGIN}${path}/`;
}
