/** From Walkers Advisors Tracking Sheet – 2026-05-18 */
import { ROUTE_SEO_OVERRIDES } from './routeSeoOverrides';
import { normalizeRoutePath } from './pathUtils';

export const HOME_ROUTE_SEO = {
  title: 'Best Walkers for Seniors | Unbiased Reviews – The Walker Advisor',
  description: 'Unbiased reviews of the best walkers for seniors. Compare top brands and ratings to find the safest, most comfortable mobility aids',
};

export const ROUTE_SEO = {
  "/16-best-christmas-gifts-for-seniors-amazon-2025": { title: "Best Christmas Gifts for Elderly Women & Seniors 2025", description: "Discover 16 thoughtful Christmas gifts for elderly women and seniors in 2025, practical, heartwarming, and perfect for your older loved ones, all available on Amazon." },
  "/inexpensive-christmas-gift-ideas-for-senior-citizens": { title: "Gifts for Seniors Under $20: 20 Affordable Ideas", description: "Find 20 thoughtful, inexpensive gifts for seniors under $20, useful, safe, and meaningful options for older adults." },
  "/5-best-upright-walkers-for-seniors-find-the-right-one": { title: "5 Best Upright Walkers for Seniors – Find the Right One", description: "Discover the 5 best upright walkers for seniors. Find the right one for stability, comfort, and mobility. See our top pick and key features!" },
  "/about-us": { title: "About Us - The Walker Advisor", description: "Learn about The Walker Advisor, your trusted source for expert reviews on walkers, rollators, and mobility aids, helping seniors find reliable solutions." },
  "/best-heavy-duty-walkers-for-obese-seniors": { title: "Best Heavy-Duty Walkers for Obese Seniors (2025)", description: "Discover the 5 best heavy-duty walkers for obese seniors in 2025. Safe, durable, and Amazon-available picks with up to 500 lb capacity." },
  "/best-mobility-devices-for-seniors": { title: "Best Mobility Devices for Seniors (2026 Guide)", description: "Discover the best mobility devices for seniors to improve safety, comfort, and independence. Compare walkers, canes, wheelchairs, and scooters." },
  "/best-small-walkers-for-seniors-top-4-options": { title: "Top 4 Small Walkers for Seniors: Best Compact Options", description: "Discover the top 4 small walkers for seniors! Find the perfect compact, lightweight, foldable walker to enhance mobility and independence." },
  "/best-travel-walkers-for-seniors-2025": { title: "Best Travel Walkers for Seniors 2025", description: "Discover 2025's top travel walkers for seniors,lightweight, foldable, and perfect for comfort, mobility, and independence on the go." },
  "/best-upright-walkers-for-outdoor-use-2025": { title: "Best Upright Walkers for Outdoor Use 2025", description: "Discover the top 5 upright walkers for outdoor use in 2025 on Amazon. All-terrain wheels, shock absorption, lightweight & stable, perfect for seniors!" },
  "/best-walking-shoes-for-seniors-2026": { title: "Best Walking Shoes for Seniors 2026: A Comprehensive Guide", description: "Top walking shoes for seniors in 2026 comfortable, stable, and supportive picks with pros, cons, and Amazon links to stay active pain-free and safe daily." },
  "/tips-for-choosing-and-using-walkers-a-comprehensive-guide": { title: "Tips for Choosing and Using Walkers | The Walker Advisor", description: "Learn how to choose the right walker and use it safely. This complete guide offers tips on types, features, and safety to enhance mobility and independence." },
  "/can-heart-issues-increase-fall-risk-in-seniors": { title: "Can Heart Issues Increase Fall Risk in Seniors?", description: "Discover how heart conditions like arrhythmia, low blood pressure, and heart failure can increase fall risk in seniors, and what you can do to stay safe" },
  "/can-osteoarthritis-lead-to-more-falls-in-seniors": { title: "Osteoarthritis and Fall Risk in Seniors", description: "Learn how osteoarthritis increases fall risk in seniors and discover simple ways to improve balance, mobility, and safety." },
  "/caregivers-guide-to-senior-walker-selection-and-usage": { title: "Caregiver's Guide to Senior Walker Selection & Usage", description: "Discover how caregivers can assist seniors in choosing, fitting, and safely using walkers. Practical tips for improving mobility and independence. Read now!" },
  "/christmas-gift-ideas-for-elderly-ladies-december-2025": { title: "Christmas Gifts for Elderly Ladies 2025", description: "Discover thoughtful Christmas gift ideas for elderly ladies this December 2025, practical, heartwarming, and perfect for your loved ones." },
  "/compact-walkers-for-seniors": { title: "Best Compact Walkers for Seniors", description: "Explore top compact walkers for seniors: lightweight, foldable aids for better mobility. Reviews, Amazon links, pros/cons, and tips to choose the right one for independence" },
  "/contact-us": { title: "Contact Us - The Walker Advisor", description: "Get in touch with The Walker Advisor for expert guidance on mobility aids. We're here to answer your questions and help you find the best solutions." },
  "/elenker-vs-nova-upright-walkers-2025": { title: "Elenker vs Nova Upright Walkers: 2025 Comparison", description: "Compare Elenker and Nova upright walkers in 2025. Discover key differences, features, pros, cons, and which brand best suits your senior mobility needs." },
  "/emergency-preparedness-for-walker-users": { title: "Top Medical Alert Devices for Walker Users Stay Safe Now", description: "Ensure safety with top medical alert systems for walker users. Discover smart tech, wearable devices, and emergency preparedness tips. Learn more inside!" },
  "/free-amazon-returns-guide": { title: "Free Amazon Returns: Complete Hassle-Free Guide", description: "Discover all ways to return Amazon orders for free with this step-by-step guide. Save time and money with hassle-free returns!" },
  "/how-to-use-walker-large-wheels-seniors-safely": { title: "Helpful Suggestions for Using a New Walker with Larger Wheels", description: "Explore useful tips for seniors on using a new walker with larger wheels. These expert suggestions will enhance safety, stability, and mobility." },
  "/heavy-duty-walkers-for-tall-people": { title: "Best Walkers for Tall People", description: "Discover top heavy-duty walkers for tall individuals with adjustable heights, high weight capacities, and comfort features. Reviews, pros, cons, and Amazon links included for easy shopping." },
  "/holiday-safety-tips-for-seniors": { title: "Holiday Safety Tips for Seniors", description: "Keep seniors safe this holiday with tips on falls, fire, décor, and wellness for a joyful, worry-free season." },
  "/holiday-safety-tips-seniors-using-walkers": { title: "Holiday Safety Tips for Seniors Using Walkers", description: "Merry and safe holidays for walker users! Clear paths, crowd navigation, gift safety, winter weather tips, and more to help seniors enjoy Christmas confidently." },
  "/how-do-supportive-grips-on-walkers-help-seniors-with-mobility": { title: "How Supportive Grips on Walkers Help Seniors' Mobility", description: "Learn how supportive grips on walkers improve mobility, safety, and comfort for seniors, enhancing their quality of life and independence." },
  "/how-to-adjust-a-walker-to-the-correct-height": { title: "Walker Height Guide: Safe Use for Seniors", description: "Learn how to set the correct walker height for seniors to improve posture, ensure comfort, and reduce fall risks with easy expert tips." },
  "/how-to-choose-walking-shoes-for-balance-and-stability": { title: "How to Choose Walking Shoes for Stability", description: "Learn how to choose walking shoes for better balance and stability with expert tips on support, cushioning, grip, and proper fit." },
  "/how-to-transition-from-a-walker-to-walking-independently": { title: "Transitioning From Walker to Walking Alone", description: "Ready to walk without a walker? Follow expert tips, step-by-step guidance, and therapy exercises to safely regain independent mobility." },
  "/how-to-travel-with-a-walker": { title: "Travel Safely with a Walker: Senior Tips", description: "Discover expert travel tips for seniors using walkers. Learn how to pack, plan, and move with confidence. Start your safe journey today!" },
  "/how-to-use-a-walker-with-wheels": { title: "How To Use A Walker With Wheels Safely – Complete Guide", description: "Learn how to use a walker with wheels safely and effectively. Step-by-step instructions, tips for seniors, and safety precautions to improve mobility and independence." },
  "/mental-health-in-old-age": { title: "Mental Health in Old Age: Causes, Signs & Practical Support Guide", description: "Discover the causes, warning signs, and proven strategies to protect mental health in old age. A complete expert guide for seniors, caregivers, and families by The Walker Advisor." },
  "/what-is-the-proper-way-to-use-a-walker": { title: "What Is the Proper Way to Use a Walker | The Walker Advisor", description: "Learn the proper way to use a walker for safety and stability. Discover tips for adjusting height, walking posture, and navigating steps with confidence." },
  "/must-have-walker-accessories-to-make-life-easier-and-safer": { title: "Essential Walker Accessories for Safety & Comfort", description: "Discover must-have walker accessories that boost safety, comfort, and independence. Learn how to customize your walker with expert-approved add-ons." },
  "/walker-safety-tips-for-all-weather-conditions": { title: "Walker Safety Tips for All Weather Conditions", description: "Stay safe in rain, snow or heat with essential walker safety tips. Learn weather-specific strategies for stability & confidence outdoors. Keep moving in any season!" },
  "/replacement-walker-hand-grips-for-all-kinds-of-walkers": { title: "Replacement Walker Hand Grips for All Kinds of Walkers", description: "Discover the best replacement walker hand grips for seniors. Learn who needs them, types available, and top Amazon picks. Find comfort & stability, learn more today." },
  "/senior-safety-how-to-use-a-walker-on-stairs": { title: "Safe Ways to Use a Walker on Stairs – Senior Guide", description: "Can seniors safely use a walker on stairs? The Walker Advisor reveals why most walkers are dangerous on stairs, the only safe techniques, and smarter long-term solutions." },
  "/an-easy-guide-on-how-to-fit-a-walker-for-seniors": { title: "How to Fit a Walker for Seniors Safely", description: "Step-by-step guide to fitting a walker for seniors. Learn types, adjustments, and tips to boost safety, comfort, and independence today." },
  "/tips-using-walker-small-homes": { title: "The Ultimate Guide to Using a Walker in Small Homes", description: "Learn space-saving strategies for safe walker use in small homes. Optimize your home layout and choose the right walker for enhanced mobility." },
  "/where-to-buy-walkers-for-seniors-top-brands-reviews": { title: "Where to Buy Walkers for Seniors - Best Options & Tips", description: "Find the best places to buy walkers for seniors. Explore trusted stores, compare prices, and learn tips to choose the best mobility aid for their needs." },
  "/best-holiday-gifts-for-seniors-who-have-everything": { title: "Best Holiday Gifts for Seniors Who Have Everything", description: "Discover thoughtful and unique holiday gifts for seniors who have everything. Perfect options to surprise and delight your loved ones." },
  "/types-of-medical-walkers-and-rollators-a-comprehensive-guide": { title: "Types of Medical Walkers and Rollators: A Comprehensive Guide", description: "Explore the different types of medical walkers and rollators. Understand their features, benefits, and how to choose the right one for mobility needs." },
  "/important-safety-features-walkers-for-seniors": { title: "Essential Safety Features in Walkers for Seniors | Best Options", description: "Discover key safety features in walkers for seniors, including sturdy frames, ergonomic grips, and reliable brakes, to enhance mobility, stability, and confidence." },
  "/the-secret-amazon-shopping-hack-to-get-a-deal-on-just-about-anything": { title: "Secret Amazon Hack to Save on Anything", description: "Learn how to save big with Amazon Warehouse deals and coupons, get discounts on almost any product without waiting for sales." },
  "/the-side-effects-of-using-a-cane": { title: "Cane Side Effects & Safer Alternatives", description: "Learn cane side effects, prevention tips, and smart alternatives like walkers. Expert insights from The Walker Advisor." },
  "/best-4-wheel-walkers-with-seats": { title: "Top Options to Consider in a 4-Wheel Walker with Seats", description: "Shopping for a 4-wheel walker with a seat? Discover what features to look for, safety tips, expert-backed insights, and product comparison. Learn more now." },
  "/understanding-upright-walkers-senior-posture": { title: "Upright Walkers for Seniors, Improve Posture & Mobility", description: "Learn how upright walkers improve senior posture, enhance balance, and reduce strain. Explore benefits, tips, and top features for healthier walking." },
  "/valentines-day-gift-ideas-for-seniors": { title: "Valentine's Day Gifts for Senior Couples", description: "Discover meaningful Valentine's Day gift ideas for senior couples focused on comfort, memories, and lasting love." },
  "/valentines-day-ideas": { title: "Valentine's Day Ideas for Seniors", description: "Simple, heartfelt Valentine's Day gifts and moments seniors will cherish, love that grows stronger with time." },
  "/why-seniors-need-proper-walking-shoes": { title: "Why Seniors Need Walking Shoes", description: "Learn how proper walking shoes keep seniors safe, reduce joint pain, and prevent falls." },
  "/does-medicare-pay-for-walkers-for-seniors": { title: "Does Medicare Cover Walkers for Seniors? | The Walker Advisor", description: "Uncover how Medicare covers walkers for seniors. Explore eligibility, coverage details, types of walkers, and expert tips at The Walker Advisor—your trusted mobility guide." },
};

export function getSeoForRoute(pathname) {
  const path = normalizeRoutePath(pathname);
  if (path === '/') return HOME_ROUTE_SEO;
  return ROUTE_SEO_OVERRIDES[path] ?? ROUTE_SEO[path] ?? null;
}
